version: '3.8'

services:
  ftp-server:
    environment:
      - FTP_PASS=12345678
      - FTP_USER=user
    image: garethflowers/ftp-server
    ports:
      - '20-21:20-21/tcp'
      - '40000-40009:40000-40009/tcp' # Only needed for passive mode
    volumes:
      - ${MEDIA_LIBRARY_PATH}:/home/user

  media-browser:
    image: filebrowser/filebrowser
    ports:
      - ${FILE_BROWSER_PORT}:80
    volumes:
      - ${MEDIA_LIBRARY_PATH}:/srv
    environment:
      - FB_NOAUTH=1

  cast-service:
    build:
      context: .
      dockerfile: Dockerfile.service
    network_mode: "host" # run in host mode to be able to discover devices
    volumes:
      - ${MEDIA_LIBRARY_PATH}:/cast/media
    environment:
      - PORT=${SERVICE_PORT}
      - MEDIA_LIBRARY_PATH=/cast/media
    healthcheck:
      start_period: 5s
      interval: 10s
      retries: 20
      test: curl --fail --silent --insecure http://127.0.0.1:${SERVICE_PORT}/ --output /dev/null || exit 1

  cast-ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
      args:
        - SERVICE_URL=http://${SERVICE_HOST}:${SERVICE_PORT}
    ports:
      - ${WEB_PORT}:80
